apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-application
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: react-application
  template:
    metadata:
      labels:
        run: react-application
    spec:
      containers:
      - name: react-application
        image: nginx
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
