apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: Helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux-chart/flux-chart
      sourceRef:
        kind: GitRepository
        name:  react-app
  interval: 10m0s
  targetNamespace: helmspace
