apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-app2
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/venkallex/flux2.git
  ref:
    branch: main
  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: react-app2
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./manifests
  prune: false
  sourceRef:
    kind: GitRepository
    name: react-app2
  
