apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/venkallex/flux2
  ref:
    branch: main
  #ignore: |
   # # exclude all
    #/*
    # include charts directory
    #!/flux-chart/ 
