apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-app
spec:
  interval: 1m
  url: https://github.com/venkallex/flux2.git
  ref:
    branch: main
  ignore: |  
    # exclude all
    /*
    # include charts directory
    !/manifests/
    !/flux-chart/
